In [1]:
from google.colab import files

uploaded = files.upload()

Saving dynamic_supply_chain_logistics_dataset.csv to dynamic_supply_chain_logistics_dataset.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("dynamic_supply_chain_logistics_dataset.csv")

In [4]:
df.head()

,timestamp,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,...,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation
0,2021-01-01 00:00:00,40.375568,-77.014318,5.136512,4.998009,5.927586,985.716862,4.951392,0.481294,0.761166,...,0.574400,0.777263,1.182116,0.502006,0.033843,0.978599,0.506152,0.885291,Moderate Risk,9.110682
1,2021-01-01 01:00:00,33.507818,-117.036902,5.101512,0.984929,1.591992,396.700206,1.030379,0.620780,0.196594,...,-9.753493,0.091839,9.611988,0.966774,0.201725,0.918586,0.980784,0.544178,High Risk,8.175281
2,2021-01-01 02:00:00,30.020640,-75.269224,5.090803,4.972665,8.787765,832.408935,4.220229,0.810933,0.152742,...,-6.491034,0.253529,6.570431,0.945627,0.264045,0.394215,0.998633,0.803322,High Risk,1.283594
3,2021-01-01 03:00:00,36.649223,-70.190529,8.219558,3.095064,0.045257,0.573283,0.530186,0.008525,0.811885,...,-0.151276,0.877576,0.548952,4.674035,0.362885,0.905444,0.993320,0.025977,High Risk,9.304897
4,2021-01-01 04:00:00,30.001279,-70.012195,5.000075,3.216077,8.004851,914.925067,3.620890,0.020083,0.053659,...,2.429448,0.262081,8.861443,3.445429,0.016957,0.258702,0.912433,0.991122,High Risk,7.752484

In [5]:
df.shape

(32065, 26)

In [6]:
df.columns

Index(['timestamp', 'vehicle_gps_latitude', 'vehicle_gps_longitude',
       'fuel_consumption_rate', 'eta_variation_hours',
       'traffic_congestion_level', 'warehouse_inventory_level',
       'loading_unloading_time', 'handling_equipment_availability',
       'order_fulfillment_status', 'weather_condition_severity',
       'port_congestion_level', 'shipping_costs', 'supplier_reliability_score',
       'lead_time_days', 'historical_demand', 'iot_temperature',
       'cargo_condition_status', 'route_risk_level', 'customs_clearance_time',
       'driver_behavior_score', 'fatigue_monitoring_score',
       'disruption_likelihood_score', 'delay_probability',
       'risk_classification', 'delivery_time_deviation'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   timestamp                        32065 non-null  object
 1   vehicle_gps_latitude             32065 non-null  float64
 2   vehicle_gps_longitude            32065 non-null  float64
 3   fuel_consumption_rate            32065 non-null  float64
 4   eta_variation_hours              32065 non-null  float64
 5   traffic_congestion_level         32065 non-null  float64
 6   warehouse_inventory_level        32065 non-null  float64
 7   loading_unloading_time           32065 non-null  float64
 8   handling_equipment_availability  32065 non-null  float64
 9   order_fulfillment_status         32065 non-null  float64
 10  weather_condition_severity       32065 non-null  float64
 11  port_congestion_level            32065 non-null  float64
 12  shipping_costs                   32065 non-null  float64
 13  supplier_reliability_score       32065 non-null  float64
 14  lead_time_days                   32065 non-null  float64
 15  historical_demand                32065 non-null  float64
 16  iot_temperature                  32065 non-null  float64
 17  cargo_condition_status           32065 non-null  float64
 18  route_risk_level                 32065 non-null  float64
 19  customs_clearance_time           32065 non-null  float64
 20  driver_behavior_score            32065 non-null  float64
 21  fatigue_monitoring_score         32065 non-null  float64
 22  disruption_likelihood_score      32065 non-null  float64
 23  delay_probability                32065 non-null  float64
 24  risk_classification              32065 non-null  object
 25  delivery_time_deviation          32065 non-null  float64
dtypes: float64(24), object(2)
memory usage: 6.4+ MB

In [8]:
df.isnull().sum()

timestamp                          0
vehicle_gps_latitude               0
vehicle_gps_longitude              0
fuel_consumption_rate              0
eta_variation_hours                0
traffic_congestion_level           0
warehouse_inventory_level          0
loading_unloading_time             0
handling_equipment_availability    0
order_fulfillment_status           0
weather_condition_severity         0
port_congestion_level              0
shipping_costs                     0
supplier_reliability_score         0
lead_time_days                     0
historical_demand                  0
iot_temperature                    0
cargo_condition_status             0
route_risk_level                   0
customs_clearance_time             0
driver_behavior_score              0
fatigue_monitoring_score           0
disruption_likelihood_score        0
delay_probability                  0
risk_classification                0
delivery_time_deviation            0
dtype: int64

In [9]:
df.isnull().sum().sum()

np.int64(0)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe()

,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,weather_condition_severity,...,historical_demand,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,delivery_time_deviation
count,32065.000000,32065.000000,32065.000000,32065.000000,3.206500e+04,3.206500e+04,32065.000000,3.206500e+04,32065.000000,3.206500e+04,...,32065.000000,32065.000000,3.206500e+04,32065.000000,32065.000000,3.206500e+04,3.206500e+04,32065.000000,32065.000000,32065.000000
mean,38.023589,-90.116648,8.011735,2.893068,4.991493e+00,2.992547e+02,2.291669,3.026954e-01,0.600740,4.976082e-01,...,6022.001286,0.044792,2.972816e-01,7.001144,2.296448,4.983913e-01,6.008723e-01,0.803656,0.699077,5.177648
std,6.917909,17.369244,4.264960,2.274044,3.532048e+00,3.234435e+02,1.554202,3.259146e-01,0.345672,3.532853e-01,...,3427.638017,14.187486,3.216115e-01,3.236328,1.555932,3.541589e-01,3.458101e-01,0.279185,0.324514,4.157988
min,30.000000,-119.999998,5.000000,-1.999993,1.091633e-09,1.322210e-12,0.500000,4.565769e-16,0.000001,4.536949e-09,...,100.002966,-10.000000,7.255415e-19,0.000050,0.500000,4.043927e-09,3.269508e-07,0.000048,0.000003,-1.999998
25%,31.280550,-106.253913,5.019984,1.185744,1.474720e+00,1.605163e+01,0.774798,1.710828e-02,0.277096,1.440135e-01,...,2822.607616,-9.931074,1.678269e-02,4.593407,0.776166,1.443567e-01,2.783148e-01,0.693739,0.456009,1.269197
50%,36.413820,-86.293414,5.636036,3.882059,4.981244e+00,1.572880e+02,1.917121,1.595151e-01,0.680553,4.961781e-01,...,6785.123209,-7.858681,1.549760e-01,8.385605,1.938273,4.988468e-01,6.831130e-01,0.958128,0.839599,6.113662
75%,44.453655,-73.079367,9.669944,4.884355,8.534902e+00,5.405980e+02,3.734188,5.535954e-01,0.938160,8.498226e-01,...,9374.252913,6.024012,5.405408e-01,9.836152,3.750817,8.510762e-01,9.372889e-01,0.998746,0.982391,9.249206
max,50.000000,-70.000000,19.999875,5.000000,9.999999e+00,9.999993e+02,5.000000,9.999995e-01,1.000000,1.000000e+00,...,10000.000000,39.999886,1.000000e+00,10.000000,5.000000,1.000000e+00,1.000000e+00,1.000000,1.000000,10.000000

In [12]:
df["timestamp"].dtype

dtype('O')

In [13]:
df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    errors="coerce"
)

In [14]:
df["timestamp"].dtype

dtype('<M8[ns]')

In [15]:
df["order_fulfillment_status"].value_counts()

order_fulfillment_status
0.985761    1
0.980944    1
0.125700    1
0.708827    1
0.967058    1
           ..
0.397323    1
0.053659    1
0.811885    1
0.152742    1
0.196594    1
Name: count, Length: 32065, dtype: int64

In [16]:
df["risk_classification"].value_counts()

risk_classification
High Risk        23944
Moderate Risk     5011
Low Risk          3110
Name: count, dtype: int64

In [17]:
df["cargo_condition_status"].value_counts()

cargo_condition_status
0.876529    1
0.388209    1
0.039450    1
0.035561    1
0.010244    1
           ..
0.041378    1
0.262081    1
0.877576    1
0.253529    1
0.091839    1
Name: count, Length: 32065, dtype: int64

In [18]:
print(
    "Negative inventory:",
    (df["warehouse_inventory_level"] < 0).sum()
)

print(
    "Negative shipping costs:",
    (df["shipping_costs"] < 0).sum()
)

print(
    "Negative lead time:",
    (df["lead_time_days"] < 0).sum()
)

print(
    "Negative historical demand:",
    (df["historical_demand"] < 0).sum()
)

print(
    "Negative fuel consumption:",
    (df["fuel_consumption_rate"] < 0).sum()
)

Negative inventory: 0
Negative shipping costs: 0
Negative lead time: 0
Negative historical demand: 0
Negative fuel consumption: 0

In [19]:
invalid_latitude = (
    (df["vehicle_gps_latitude"] < -90) |
    (df["vehicle_gps_latitude"] > 90)
).sum()

invalid_longitude = (
    (df["vehicle_gps_longitude"] < -180) |
    (df["vehicle_gps_longitude"] > 180)
).sum()

print("Invalid latitude:", invalid_latitude)
print("Invalid longitude:", invalid_longitude)

Invalid latitude: 0
Invalid longitude: 0

In [20]:
df.head()
df.shape
df.info()
df.isnull().sum()
df.duplicated().sum()
df.describe().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   timestamp                        32065 non-null  datetime64[ns]
 1   vehicle_gps_latitude             32065 non-null  float64
 2   vehicle_gps_longitude            32065 non-null  float64
 3   fuel_consumption_rate            32065 non-null  float64
 4   eta_variation_hours              32065 non-null  float64
 5   traffic_congestion_level         32065 non-null  float64
 6   warehouse_inventory_level        32065 non-null  float64
 7   loading_unloading_time           32065 non-null  float64
 8   handling_equipment_availability  32065 non-null  float64
 9   order_fulfillment_status         32065 non-null  float64
 10  weather_condition_severity       32065 non-null  float64
 11  port_congestion_level            32065 non-null  float64
 12  shipping_costs                   32065 non-null  float64
 13  supplier_reliability_score       32065 non-null  float64
 14  lead_time_days                   32065 non-null  float64
 15  historical_demand                32065 non-null  float64
 16  iot_temperature                  32065 non-null  float64
 17  cargo_condition_status           32065 non-null  float64
 18  route_risk_level                 32065 non-null  float64
 19  customs_clearance_time           32065 non-null  float64
 20  driver_behavior_score            32065 non-null  float64
 21  fatigue_monitoring_score         32065 non-null  float64
 22  disruption_likelihood_score      32065 non-null  float64
 23  delay_probability                32065 non-null  float64
 24  risk_classification              32065 non-null  object
 25  delivery_time_deviation          32065 non-null  float64
dtypes: datetime64[ns](1), float64(24), object(1)
memory usage: 6.4+ MB

,count,mean,min,25%,50%,75%,max,std
timestamp,32065,2022-10-31 00:00:00.000000256,2021-01-01 00:00:00,2021-12-01 00:00:00,2022-10-31 00:00:00,2023-09-30 00:00:00,2024-08-29 00:00:00,NaN
vehicle_gps_latitude,32065.0,38.023589,30.0,31.28055,36.41382,44.453655,50.0,6.917909
vehicle_gps_longitude,32065.0,-90.116648,-119.999998,-106.253913,-86.293414,-73.079367,-70.0,17.369244
fuel_consumption_rate,32065.0,8.011735,5.0,5.019984,5.636036,9.669944,19.999875,4.26496
eta_variation_hours,32065.0,2.893068,-1.999993,1.185744,3.882059,4.884355,5.0,2.274044
traffic_congestion_level,32065.0,4.991493,0.0,1.47472,4.981244,8.534902,9.999999,3.532048
warehouse_inventory_level,32065.0,299.254732,0.0,16.051635,157.288022,540.597991,999.999298,323.443513
loading_unloading_time,32065.0,2.291669,0.5,0.774798,1.917121,3.734188,5.0,1.554202
handling_equipment_availability,32065.0,0.302695,0.0,0.017108,0.159515,0.553595,0.999999,0.325915
order_fulfillment_status,32065.0,0.60074,0.000001,0.277096,0.680553,0.93816,1.0,0.345672
weather_condition_severity,32065.0,0.497608,0.0,0.144014,0.496178,0.849823,1.0,0.353285
port_congestion_level,32065.0,6.978414,0.000002,4.513889,8.383225,9.83815,10.0,3.251051
shipping_costs,32065.0,459.374452,100.0,154.017124,388.996911,753.007203,999.999853,312.183487
supplier_reliability_score,32065.0,0.50085,0.0,0.145316,0.503266,0.853978,1.0,0.353528
lead_time_days,32065.0,5.227502,1.0,1.23749,3.297654,8.62572,14.999995,4.523085
historical_demand,32065.0,6022.001286,100.002966,2822.607616,6785.123209,9374.252913,10000.0,3427.638017
iot_temperature,32065.0,0.044792,-10.0,-9.931074,-7.858681,6.024012,39.999886,14.187486
cargo_condition_status,32065.0,0.297282,0.0,0.016783,0.154976,0.540541,1.0,0.321611
route_risk_level,32065.0,7.001144,0.00005,4.593407,8.385605,9.836152,10.0,3.236328
customs_clearance_time,32065.0,2.296448,0.5,0.776166,1.938273,3.750817,5.0,1.555932
driver_behavior_score,32065.0,0.498391,0.0,0.144357,0.498847,0.851076,1.0,0.354159
fatigue_monitoring_score,32065.0,0.600872,0.0,0.278315,0.683113,0.937289,1.0,0.34581
disruption_likelihood_score,32065.0,0.803656,0.000048,0.693739,0.958128,0.998746,1.0,0.279185
delay_probability,32065.0,0.699077,0.000003,0.456009,0.839599,0.982391,1.0,0.324514
delivery_time_deviation,32065.0,5.177648,-1.999998,1.269197,6.113662,9.249206,10.0,4.157988

In [21]:
df["risk_classification"].value_counts()

risk_classification
High Risk        23944
Moderate Risk     5011
Low Risk          3110
Name: count, dtype: int64

In [22]:
df["risk_classification"].unique()

array(['Moderate Risk', 'High Risk', 'Low Risk'], dtype=object)

In [23]:
print("Negative inventory:",
      (df["warehouse_inventory_level"] < 0).sum())

print("Negative shipping costs:",
      (df["shipping_costs"] < 0).sum())

print("Negative lead time:",
      (df["lead_time_days"] < 0).sum())

print("Negative historical demand:",
      (df["historical_demand"] < 0).sum())

print("Negative fuel consumption:",
      (df["fuel_consumption_rate"] < 0).sum())

print("\nGPS CHECK")

invalid_latitude = (
    (df["vehicle_gps_latitude"] < -90) |
    (df["vehicle_gps_latitude"] > 90)
).sum()

invalid_longitude = (
    (df["vehicle_gps_longitude"] < -180) |
    (df["vehicle_gps_longitude"] > 180)
).sum()

print("Invalid latitude:", invalid_latitude)
print("Invalid longitude:", invalid_longitude)

Negative inventory: 0
Negative shipping costs: 0
Negative lead time: 0
Negative historical demand: 0
Negative fuel consumption: 0

GPS CHECK
Invalid latitude: 0
Invalid longitude: 0

In [24]:
def find_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower_bound) |
        (data[column] > upper_bound)
    ]

    return outliers, lower_bound, upper_bound

In [25]:
columns_to_check = [
    "warehouse_inventory_level",
    "historical_demand",
    "shipping_costs",
    "lead_time_days"
]

for column in columns_to_check:
    outliers, lower, upper = find_outliers_iqr(df, column)

    print("\nColumn:", column)
    print("Lower bound:", lower)
    print("Upper bound:", upper)
    print("Number of potential outliers:", len(outliers))

Column: warehouse_inventory_level
Lower bound: -770.7678991453372
Upper bound: 1327.4175251678007
Number of potential outliers: 0

Column: historical_demand
Lower bound: -7004.8603296820065
Upper bound: 19201.72085848233
Number of potential outliers: 0

Column: shipping_costs
Lower bound: -744.4679956682228
Upper bound: 1651.4923223877004
Number of potential outliers: 0

Column: lead_time_days
Lower bound: -9.844855798262639
Upper bound: 19.708066177077075
Number of potential outliers: 0

In [26]:
numeric_columns = df.select_dtypes(include="number").columns

print("Number of numerical columns:", len(numeric_columns))
print("\nNumerical columns:")
print(numeric_columns.tolist())

Number of numerical columns: 24

Numerical columns:
['vehicle_gps_latitude', 'vehicle_gps_longitude', 'fuel_consumption_rate', 'eta_variation_hours', 'traffic_congestion_level', 'warehouse_inventory_level', 'loading_unloading_time', 'handling_equipment_availability', 'order_fulfillment_status', 'weather_condition_severity', 'port_congestion_level', 'shipping_costs', 'supplier_reliability_score', 'lead_time_days', 'historical_demand', 'iot_temperature', 'cargo_condition_status', 'route_risk_level', 'customs_clearance_time', 'driver_behavior_score', 'fatigue_monitoring_score', 'disruption_likelihood_score', 'delay_probability', 'delivery_time_deviation']

In [27]:
df["risk_classification"].value_counts()
df["risk_classification"].unique()

array(['Moderate Risk', 'High Risk', 'Low Risk'], dtype=object)

In [28]:
cleaned_df = df.copy()

In [29]:
cleaned_df.to_csv(
    "logistics_cleaned.csv",
    index=False
)

In [30]:
import os

print(os.path.exists("logistics_cleaned.csv"))

True

In [31]:
from google.colab import files

files.download("logistics_cleaned.csv")